language: ruby
sudo: false
cache: bundler
script:
- bundle exec rake spec
rvm:
- 2.0.0
- 2.1.5
- 2.5.2
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  on:
    rvm: 2.1.5
    tags: true
    all_branches: true
notifications: 
email: false
